import sequelize from "@/database"; import User from "@/models/user-model"; import Funcionario from "@/models/funcionario-model"; import Cargo from "@/models/cargo-model"; import Entregador from "@/models/entregador-model"; import { BcryptAdapter } from "@/adapters/bcrypt-adapter"; import { ENV } from "@/config/env";
const include=[{model:User,as:"user",attributes:{exclude:["senha"]}},{model:Cargo,as:"cargo"},{model:Entregador,as:"entregador",required:false}];
export class FuncionarioService {
 async listar(){return Funcionario.findAll({include,order:[["nome","ASC"]]});}
 async buscar(id:number){const f=await Funcionario.findByPk(id,{include});if(!f)throw new Error("Funcionário não encontrado.");return f;}
 async emailExiste(email:string,ignorar?:number){const u=await User.findOne({where:{email:email.toLowerCase()}});if(!u)return false;if(!ignorar)return true;const f=await Funcionario.findByPk(ignorar);return !f||f.userId!==u.id;}
 async criar(d:any){return sequelize.transaction(async t=>{if(await User.findOne({where:{email:d.email.toLowerCase()},transaction:t}))throw new Error("Este e-mail já está em uso.");const cargo=await Cargo.findByPk(Number(d.cargoId),{transaction:t});if(!cargo)throw new Error("Cargo não encontrado.");const hash=await new BcryptAdapter(ENV.SALT).hash(d.senha);const user=await User.create({nome:d.nome.trim(),email:d.email.toLowerCase().trim(),senha:hash,role:"Funcionario"},{transaction:t});const f=await Funcionario.create({nome:d.nome.trim(),telefone:d.telefone||null,ativo:d.ativo??true,userId:user.id,cargoId:cargo.id},{transaction:t});return (await Funcionario.findByPk(f.id,{include,transaction:t}))!;});}
 async atualizar(id:number,d:any){return sequelize.transaction(async t=>{const f=await Funcionario.findByPk(id,{include:[{model:User,as:"user"}],transaction:t});if(!f)throw new Error("Funcionário não encontrado.");const user=(f as any).user as User;if(d.email&&d.email.toLowerCase()!==user.email&&await User.findOne({where:{email:d.email.toLowerCase()},transaction:t}))throw new Error("Este e-mail já está em uso.");const userData:any={};if(d.nome)userData.nome=d.nome.trim();if(d.email)userData.email=d.email.toLowerCase().trim();if(d.senha)userData.senha=await new BcryptAdapter(ENV.SALT).hash(d.senha);if(Object.keys(userData).length)await user.update(userData,{transaction:t});await f.update({nome:d.nome?.trim()??f.nome,telefone:d.telefone!==undefined?(d.telefone||null):f.telefone,ativo:d.ativo??f.ativo,cargoId:d.cargoId??f.cargoId},{transaction:t});return (await Funcionario.findByPk(id,{include,transaction:t}))!;});}
 async excluir(id:number){return sequelize.transaction(async t=>{const f=await Funcionario.findByPk(id,{transaction:t});if(!f)throw new Error("Funcionário não encontrado.");const userId=f.userId;await Entregador.destroy({where:{funcionarioId:id},transaction:t});await f.destroy({transaction:t});await User.destroy({where:{id:userId},transaction:t});});}
}
export default new FuncionarioService();
