import { ServerError } from "../errors";
import { HttpResponse } from "../protocols";
const bodyOf=(value:any)=>value instanceof Error?{message:value.message}:value;
export const badRequest=(error:Error|string):HttpResponse=>({statusCode:400,body:bodyOf(error)});
export const serverError=(error?:Error|unknown):HttpResponse=>({statusCode:500,body:new ServerError(error)});
export const ok=(data:any):HttpResponse=>({statusCode:200,body:data});
export const created=(data:any):HttpResponse=>({statusCode:201,body:data});
export const notFound=(data:any):HttpResponse=>({statusCode:404,body:bodyOf(data)});
export const noContent=():HttpResponse=>({statusCode:204,body:null});
export const unAuthorized=(data?:any):HttpResponse=>({statusCode:401,body:bodyOf(data)});
export const forbidden=(data?:any):HttpResponse=>({statusCode:403,body:bodyOf(data)});
export const conflict=(data:any):HttpResponse=>({statusCode:409,body:bodyOf(data)});
